# 
# Rake file for building BioLib/HPC-GFF3
#

dfiles = Dir.glob("./*.d")
d_test = '-unittest'
d_debug = ''

desc "Build Biolib/HPC-GFF3"
file 'testgff3' => dfiles do
  print "dmd #{d_debug} #{d_test} -oftestgff3 #{dfiles.join(' ')}"
  sh "dmd #{d_debug} #{d_test} -oftestgff3 #{dfiles.join(' ')}"
  sh './testgff3'
end

